#!/usr/bin/env python3
"""Figure 1: per-token entropy trace of a fabrication, rendered as LaTeX.

Reads the committed per-token trace (data/entropy_trace_wombat.json) and emits a
self-contained LaTeX fragment (figures/fig1_entropy_trace.tex) that colours each
generated token by its generation entropy. The query "What shape is wombat scat?"
elicits a confidently-worded fabrication (wombat scat is cube-shaped, not
cylindrical), yet the state object shows entropy spikes exactly where the model
improvises -- the signal the text channel hides.

The entropy->bin(0..6) thresholds below are fixed and documented; they reproduce
the discrete colouring used in the paper. The `make traces` path
(scripts/generate_trace.py) regenerates the underlying trace from the model.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TRACE = ROOT / "data" / "entropy_trace_wombat.json"
OUT = ROOT / "figures" / "fig1_entropy_trace.tex"

# Fixed entropy (nats) -> bin edges. A token's bin is the number of edges its
# entropy meets or exceeds (0 = most confident, 6 = most uncertain). Placed in
# the gaps between observed per-bin ranges so the discrete colouring is stable.
BIN_EDGES = [0.19, 0.46, 1.04, 1.56, 2.02, 3.15]

# Colour definitions (blue = confident -> red = uncertain), matching the paper.
COLOR_DEFS = r"""\definecolor{ent0bg}{rgb}{0.13,0.40,0.67}\definecolor{ent0fg}{rgb}{1,1,1}
\definecolor{ent1bg}{rgb}{0.40,0.66,0.81}\definecolor{ent1fg}{rgb}{0,0,0}
\definecolor{ent2bg}{rgb}{0.97,0.97,0.97}\definecolor{ent2fg}{rgb}{0,0,0}
\definecolor{ent3bg}{rgb}{0.99,0.75,0.44}\definecolor{ent3fg}{rgb}{0,0,0}
\definecolor{ent4bg}{rgb}{0.99,0.55,0.24}\definecolor{ent4fg}{rgb}{0,0,0}
\definecolor{ent5bg}{rgb}{0.90,0.30,0.24}\definecolor{ent5fg}{rgb}{1,1,1}
\definecolor{ent6bg}{rgb}{0.84,0.19,0.15}\definecolor{ent6fg}{rgb}{1,1,1}
\newcommand{\etok}[2]{\colorbox{ent#1bg}{\strut\textcolor{ent#1fg}{\small\texttt{#2}}}\hspace{-0.5pt}}"""

LEGEND = r"""
\medskip
\noindent\footnotesize%
\colorbox{ent0bg}{\textcolor{ent0fg}{\strut\ confident\ }}
\colorbox{ent1bg}{\textcolor{ent1fg}{\strut\ low\ }}
\colorbox{ent2bg}{\textcolor{ent2fg}{\strut\ moderate\ }}
\colorbox{ent3bg}{\textcolor{ent3fg}{\strut\ elevated\ }}
\colorbox{ent4bg}{\textcolor{ent4fg}{\strut\ high\ }}
\colorbox{ent5bg}{\textcolor{ent5fg}{\strut\ very high\ }}
\colorbox{ent6bg}{\textcolor{ent6fg}{\strut\ uncertain\ }}
\hfill \textit{Per-token generation entropy (nats)}"""


def entropy_bin(entropy: float) -> int:
    return sum(entropy >= edge for edge in BIN_EDGES)


def is_special(token_text: str) -> bool:
    """Special/control tokens (e.g. <|endoftext|>) are counted in the header
    statistics but not rendered, matching the paper figure."""
    t = token_text.strip()
    return t.startswith("<|") and t.endswith("|>")


def latex_escape(text: str) -> str:
    """Escape LaTeX special characters for use inside \\texttt{...}."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#",
        "_": r"\_", "{": r"\{", "}": r"\}",
        "~": r"\textasciitilde{}", "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(ch, ch) for ch in text)


def main() -> None:
    data = json.loads(TRACE.read_text())
    tokens = data["tokens"]
    entropies = [t["entropy"] for t in tokens]
    mean_h = sum(entropies) / len(entropies)
    max_h = max(entropies)

    lines = []
    lines.append("% Figure 1 -- entropy trace (generated by scripts/fig1_entropy_trace.py)")
    lines.append("% Requires \\usepackage{xcolor} in the document preamble.")
    lines.append(COLOR_DEFS)
    lines.append("")
    lines.append(
        rf"\noindent\textbf{{Q: {latex_escape(data['query'])}}} "
        rf"--- mean $H={mean_h:.3f}$, max $H={max_h:.3f}$, {len(tokens)} tokens\\[4pt]"
    )
    lines.append(r"\noindent%")

    row = []
    rendered = 0
    for tok in tokens:
        if is_special(tok["token_text"]):
            continue
        b = entropy_bin(tok["entropy"])
        row.append(rf"\etok{{{b}}}{{{latex_escape(tok['token_text'])}}}")
        rendered += 1
        if rendered % 10 == 0:  # wrap ~10 tokens per source line, as in the paper
            lines.append("".join(row) + "%")
            row = []
    if row:
        lines.append("".join(row))
    lines.append(LEGEND)

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)}  ({len(tokens)} tokens, "
          f"mean H={mean_h:.3f}, max H={max_h:.3f})")
    rendered = [t["entropy"] for t in tokens if not is_special(t["token_text"])]
    counts = {b: sum(entropy_bin(e) == b for e in rendered) for b in range(7)}
    print(f"  {len(rendered)} rendered tokens; "
          f"bin histogram (0=confident..6=uncertain): {counts}")


if __name__ == "__main__":
    main()
